-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.4.32-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             12.10.0.7000
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping structure for table attend.attend_records
CREATE TABLE IF NOT EXISTS `attend_records` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_name` varchar(100) NOT NULL,
  `device_name` varchar(100) NOT NULL,
  `action` enum('in','out') NOT NULL,
  `ts` datetime NOT NULL,
  `lat` decimal(10,6) DEFAULT NULL,
  `lng` decimal(10,6) DEFAULT NULL,
  `in_radius` tinyint(1) DEFAULT 0,
  `message` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table attend.attend_records: ~0 rows (approximately)

-- Dumping structure for table attend.enquiries
CREATE TABLE IF NOT EXISTS `enquiries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `email_address` varchar(255) DEFAULT NULL,
  `message` text DEFAULT NULL,
  `date_created` int(11) DEFAULT NULL,
  `opened` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table attend.enquiries: ~0 rows (approximately)

-- Dumping structure for table attend.members
CREATE TABLE IF NOT EXISTS `members` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `url_string` varchar(255) DEFAULT NULL,
  `username` varchar(55) DEFAULT NULL,
  `first_name` varchar(65) DEFAULT NULL,
  `last_name` varchar(75) DEFAULT NULL,
  `email_address` varchar(255) DEFAULT NULL,
  `date_joined` int(11) NOT NULL,
  `code` varchar(16) NOT NULL,
  `password` varchar(255) NOT NULL,
  `num_logins` int(11) NOT NULL,
  `last_login` int(11) NOT NULL,
  `trongate_user_id` int(11) NOT NULL,
  `confirmed` tinyint(1) DEFAULT NULL,
  `user_token` varchar(32) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table attend.members: ~0 rows (approximately)

-- Dumping structure for table attend.news
CREATE TABLE IF NOT EXISTS `news` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `url_string` varchar(255) DEFAULT NULL,
  `article_headline` varchar(255) DEFAULT NULL,
  `sounds_like` varchar(255) NOT NULL,
  `article_body` text DEFAULT NULL,
  `date_and_time` datetime DEFAULT NULL,
  `published` tinyint(1) DEFAULT NULL,
  `code` varchar(6) NOT NULL,
  `picture` varchar(255) DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table attend.news: ~26 rows (approximately)
INSERT INTO `news` (`id`, `url_string`, `article_headline`, `sounds_like`, `article_body`, `date_and_time`, `published`, `code`, `picture`) VALUES
	(1, 'covid19-vaccines-to-be-compulsory-for-frontline-nhs-staff-in-england', 'Covid-19: Vaccines to be compulsory for frontline NHS staff in England', 'KFTFKSNSTBKMPLSRFRFRNTLNNSSTFNNKLNT', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-10-11 00:00:00', 1, '3U93VR', ''),
	(2, 'thousands-of-phone-boxes-to-be-saved-from-closure', 'Thousands of phone boxes to be saved from closure', '0SNTSFFNBKSSTBSFTFRMKLSR', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-10-12 00:00:00', 1, '8BYFYQ', ''),
	(3, 'covid-what-are-the-vaccine-rules-for-nhs-staff-and-can-i-get-a-booster', 'Covid: What are the vaccine rules for NHS staff and can I get a booster?', 'KFTHTR0FKSNRLSFRNSSTFNTKNJTBSTR', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-10-13 00:00:00', 1, '6ZCDDD', ''),
	(4, 'tech-ripple-to-launch-crypto-service-for-financial-companies-amid-legal-battle-with-the-sec', 'TECH\nRipple to launch crypto service for financial companies amid legal battle with the SEC', 'TXRPLTLNXKRPTSRFSFRFNNXLKMPNSMTLKLBTLW00SK', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-10-14 00:00:00', 1, 'DUW3MF', ''),
	(5, 'microsoft-rival-collibra-doubles-valuation-to-525-billion-as-investors-chase-next-cloud-winner', 'Microsoft rival Collibra doubles valuation to $5.25 billion as investors chase next cloud winner', 'MKRSFTRFLKLBRTBLSFLXNTBLNSNFSTRSXSNKSTKLTWNR', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-10-15 00:00:00', 1, 'SEPJMC', ''),
	(6, 'want-to-sound-more-confident-avoid-these-11-words-and-phrases-that-make-you-look-weak-say-grammar-experts', 'Want to sound more confident? Avoid these 11 words and phrases that make you look ‘weak,’ say grammar experts', 'WNTTSNTMRKNFTNTFT0SWRTSNTFRSS0TMKYLKWKSKRMRKSPRTS', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-10-16 00:00:00', 1, 'BUSURA', ''),
	(7, 'behind-the-desk-cofounder-of-16-billion-brand-skims-i-have-a-rule--you-have-to-do-things-that-scare-you', 'BEHIND THE DESK\nCo-founder of $1.6 billion brand Skims: ‘I have a rule — you have to do things that scare you’', 'BHNT0TSKKFNTRFBLNBRNTSKMSHFRLYHFTT0NKS0TSKRY', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-10-17 00:00:00', 1, 'XE84QB', ''),
	(8, 'so-your-old-boss-wants-you-to-come-backheres-how-to-negotiate-a-boomerang-offer', 'So your old boss wants you to come back—here’s how to negotiate a ‘boomerang’ offer', 'SYRLTBSWNTSYTKMBKHRSHTNKXTBMRNKFR', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-10-18 00:00:00', 1, 'BHWKDP', ''),
	(9, 'aerospace--defense-boeing-delivered-27-planes-in-october-airlines-still-waiting-on-new-dreamliners', 'AEROSPACE & DEFENSE\nBoeing delivered 27 planes in October, airlines still waiting on new Dreamliners', 'ERSPSTFNSBNKTLFRTPLNSNKTBRRLNSSTLWTNKNNTRMLNRS', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-10-19 00:00:00', 1, 'TLR6VV', ''),
	(10, 'greenwashing-or-viable-solution-europe-has-a-big-decision-to-make-on-nuclear-power', 'Greenwashing or viable solution? Europe has a big decision to make on nuclear power', 'KRNWXNKRFBLSLXNRPHSBKTSXNTMKNNKLRPWR', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-10-20 00:00:00', 1, 'PTJ3AJ', ''),
	(11, 'how-criminals-are-using-upandcoming-crypto-atms-to-commit-fraud', 'How criminals are using up-and-coming crypto ATMs to commit fraud', 'HKRMNLSRSNKPNTKMNKKRPTTMSTKMTFRT', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-10-21 00:00:00', 1, 'L67QMJ', 'atm.jpg'),
	(12, 'vector-group-ceo-howard-lorber-on-spinning-off-douglas-elliman-into-public-company', 'Vector Group CEO Howard Lorber on spinning off Douglas Elliman into public company', 'FKTRKRPSHWRTLRBRNSPNNKFTKLSLMNNTPBLKKMPN', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-10-22 00:00:00', 1, 'EMMUCF', 'street.jpg'),
	(13, 'london-stock-exchange-aims-to-bring-firms-carbon-claims-out-into-daylight', 'London Stock Exchange aims to bring firms’ carbon claims ‘out into daylight’', 'LNTNSTKKSXNJMSTBRNKFRMSKRBNKLMSTNTTLFT', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. \r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nDoloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-10-23 00:00:00', 1, 'ZNUDYT', 'windfarm.jpg'),
	(14, 'us-futures-signal-mixed-open-after-major-averages-close-at-record-highs', 'U.S. futures signal mixed open after major averages close at record highs', 'USFTRSSKNLMKSTPNFTRMJRFRJSKLSTRKRTHFS', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-10-24 00:00:00', 1, 'N5WW6T', ''),
	(15, 'jpmorgan-picks-3-chip-stocks-set-to-benefit-as-supply-chain-disruptions-ease', 'JPMorgan picks 3 chip stocks set to benefit as supply chain disruptions ease', 'JPMRKNPKSXPSTKSSTTBNFTSSPLXNTSRPXNSS', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-10-25 00:00:00', 1, '9WAFVB', ''),
	(16, 'airbnb-profits-surge-280-in-third-quarter', 'Airbnb profits surge 280% in third quarter', 'ARBNBPRFTSSRJN0RTKRTR', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-10-26 00:00:00', 1, 'KD5DAQ', ''),
	(17, 'heres-how-much-debt-millennials-have-on-average', 'Here’s how much debt millennials have on average', 'HRSHMXTBTMLNLSHFNFRJ', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-10-27 00:00:00', 1, 'BBZMRE', ''),
	(18, 'apple-intel-and-more-jefferies-just-named-its-top-cashflow-machines-to-beat-stagflation', 'Apple, Intel and more: Jefferies just named its top ‘cashflow machines’ to beat stagflation', 'APLNTLNTMRJFRSJSTNMTTSTPKXFLMXNSTBTSTKFLXN', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-10-28 00:00:00', 1, 'BKCVNN', ''),
	(19, 'these-investors-got-the-ge-trade-right-heres-what-they-say-to-do-with-the-stock-now', 'These investors got the GE trade right. Here’s what they say to do with the stock now', '0SNFSTRSKT0JTRTRFTHRSHT0STTW00STKN', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-10-29 00:00:00', 1, 'AGHUTU', 'ge.jpg'),
	(20, 'bank-of-englands-bailey-says-the-warning-signs-are-there-on-inflation', 'Bank of England’s Bailey says ‘the warning signs are there’ on inflation', 'BNKFNKLNTSBLSS0WRNNKSKNSR0RNNFLXN', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-10-30 00:00:00', 1, 'A69VSX', 'city.jpg'),
	(21, 'peloton-unveils-guide-a-strength-training-program-that-connects-to-your-tv', 'Peloton unveils Guide, a strength training program that connects to your TV', 'PLTNNFLSKTSTRNK0TRNNKPRKRM0TKNKTSTYRTF', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-10-31 00:00:00', 1, 'JJUZXE', ''),
	(22, 'chinese-auto-giant-geely-launches-electric-truck-to-rival-teslas-semi', 'Chinese auto giant Geely launches electric truck to rival Tesla’s Semi', 'XNSTJNTJLLNXSLKTRKTRKTRFLTSLSSM', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-07-04 12:00:00', 1, 'KGTH2Y', 'car.jpg'),
	(23, 'goldman-and-vwbacked-northvolt-produces-battery-cell-with-recycled-nickel-manganese-and-cobalt', 'Goldman and VW-backed Northvolt produces battery cell with recycled nickel, manganese and cobalt', 'KLTMNNTFBKTNR0FLTPRTSSBTRSLW0RSKLTNKLMNKNSNTKBLT', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-07-05 09:48:00', 1, 'DEPVYR', 'laptop.jpg'),
	(24, 'are-electric-cars-green-the-answer-is-yes-but-its-complicated', 'Are electric cars ‘green’? The answer is yes, but it’s complicated', 'ARLKTRKKRSKRN0NSWRSYSBTTSKMPLKTT', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-07-03 09:50:00', 1, 'NXF9KC', 'scientist.jpg'),
	(25, 'more-than-75-of-people-in-6-southeast-asian-countries-now-have-access-to-the-internet-report-finds', 'More than 75% of people in 6 Southeast Asian countries now have access to the internet, report finds', 'MR0NFPPLNS0STXNKNTRSNHFKSST0NTRNTRPRTFNTS', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-07-02 09:50:00', 1, 'WXQWZE', 'harbour.jpg'),
	(26, 'drones-and-f35-fighter-jet-deal-in-focus-for-the-dubai-air-show', 'Drones and F-35 fighter jet deal in focus for the Dubai Air Show', 'TRNSNTFFFTRJTTLNFKSFR0TBRX', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus earum a ex nihil adipisci, consectetur excepturi. Totam eligendi quasi cum necessitatibus quam corporis quisquam, vero, consequatur, asperiores voluptates perferendis debitis.\r\n\r\n[youtube]ZYtTeKQw80k[/youtube]\r\n\r\nVoluptas est amet, totam vel dolorem illo esse eligendi nihil fugiat veritatis! Ipsum praesentium natus aliquam tempore. Perspiciatis excepturi iusto consequatur, voluptatum illo voluptate dolorum accusamus blanditiis, libero ducimus ipsa.\r\n\r\nEos reprehenderit enim magnam aperiam vero eligendi nisi temporibus maxime quibusdam. Aliquid ad culpa necessitatibus facere voluptatem asperiores quidem sequi dolores sed cupiditate, laudantium error totam, veritatis numquam aliquam est!\r\n\r\nAnimi maiores beatae in vero quae fuga deserunt, cum fugit repellendus eligendi placeat, nisi. Temporibus, ab debitis numquam repudiandae et animi officiis placeat ducimus rem a fuga voluptatibus sequi aliquam?\r\nQuos odit perferendis perspiciatis maxime. Provident consectetur placeat voluptates vero molestiae dolor ut culpa minus, ea quod pariatur quisquam perspiciatis eos modi reiciendis, possimus earum, magni animi assumenda quis, sapiente.\r\n\r\nExpedita reprehenderit, quas distinctio, quaerat dolore est sed nobis repellat non molestias. Laborum iusto, amet, vel, incidunt voluptatem pariatur magni facere cupiditate vitae explicabo libero. Cum dignissimos, blanditiis magni voluptate.\r\nUnde aut aspernatur dolores ipsam est, animi quisquam libero ipsum ab nulla architecto corrupti at sapiente fuga maxime sequi dolore eveniet vitae pariatur quo ex eum reiciendis. Voluptate itaque, eveniet.\r\n\r\nItaque odit voluptatum molestias sint iure modi, quasi saepe doloremque laborum, ullam dignissimos quaerat adipisci dolorem porro sit magni ipsum! Amet, velit? At consequuntur minus perspiciatis iusto dolorum fuga veniam.\r\n\r\nTotam obcaecati distinctio omnis earum blanditiis assumenda qui fuga magni ullam dolorum eligendi debitis voluptatibus commodi nihil soluta similique, tempora dicta, minus? Tempore facilis quo ea saepe quam corrupti. Quia?\r\n\r\nOdit, maxime laborum omnis asperiores ducimus ipsam hic pariatur. Placeat dolore voluptate obcaecati quis ratione voluptatem, assumenda possimus inventore cumque consequatur veniam labore quos qui aliquam nostrum sunt fuga facilis.', '2021-06-27 10:38:00', 1, 'DBAWBE', 'jet.jpg');

-- Dumping structure for table attend.spam_blocker_data
CREATE TABLE IF NOT EXISTS `spam_blocker_data` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `element` varchar(255) DEFAULT NULL,
  `target_string` varchar(255) DEFAULT NULL,
  `score` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table attend.spam_blocker_data: ~0 rows (approximately)

-- Dumping structure for table attend.trongate_administrators
CREATE TABLE IF NOT EXISTS `trongate_administrators` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(65) DEFAULT NULL,
  `password` varchar(60) DEFAULT NULL,
  `trongate_user_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table attend.trongate_administrators: ~1 rows (approximately)
INSERT INTO `trongate_administrators` (`id`, `username`, `password`, `trongate_user_id`) VALUES
	(1, 'admin', '$2y$11$SoHZDvbfLSRHAi3WiKIBiu.tAoi/GCBBO4HRxVX1I3qQkq3wCWfXi', 1);

-- Dumping structure for table attend.trongate_comments
CREATE TABLE IF NOT EXISTS `trongate_comments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `comment` text DEFAULT NULL,
  `date_created` int(11) DEFAULT 0,
  `user_id` int(11) DEFAULT NULL,
  `target_table` varchar(125) DEFAULT NULL,
  `update_id` int(11) DEFAULT NULL,
  `code` varchar(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table attend.trongate_comments: ~0 rows (approximately)

-- Dumping structure for table attend.trongate_pages
CREATE TABLE IF NOT EXISTS `trongate_pages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `url_string` varchar(255) DEFAULT NULL,
  `page_title` varchar(255) DEFAULT NULL,
  `meta_keywords` text DEFAULT NULL,
  `meta_description` text DEFAULT NULL,
  `page_body` text DEFAULT NULL,
  `date_created` int(11) DEFAULT NULL,
  `last_updated` int(11) DEFAULT NULL,
  `published` tinyint(1) DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table attend.trongate_pages: ~1 rows (approximately)
INSERT INTO `trongate_pages` (`id`, `url_string`, `page_title`, `meta_keywords`, `meta_description`, `page_body`, `date_created`, `last_updated`, `published`, `created_by`) VALUES
	(1, 'homepage', 'Homepage', '', '', '<div style="text-align: center;">\n    <h1>It Totally Works!</h1>\n</div>\n<div class="text-div">\n    <p>\n        <i>Congratulations!</i> You have successfully installed Trongate.  <b>This is your homepage.</b>  Trongate was built with a focus on lightning-fast performance, while minimizing dependencies on third-party libraries. By adopting this approach, Trongate delivers not only exceptional speed but also rock-solid stability.\n    </p>\n    <p>\n        <b>You can change this page and start adding new content through the admin panel.</b>\n    </p>\n</div>\n<h2>Getting Started</h2>\n<div class="text-div">\n    <p>\n        To get started, log into the <a href="[website]tg-admin">admin panel</a>. From the admin panel, you\'ll be able to easily edit <i>this</i> page or create entirely <i>new</i> pages. The default login credentials for the admin panel are as follows:\n    </p>\n    <ul>\n        <li>Username: <b>admin</b></li>\n        <li>Password: <b>admin</b></li>\n    </ul>\n</div>\n<div class="button-div" style="cursor: pointer; font-size: 1.2em;">\n    <div style="text-align: center;">\n        <button onclick="window.location=\'[website]tg-admin\';">Admin Panel</button>\n        <button class="alt" onclick="window.location=\'https://trongate.io/docs\';">Documentation</button>\n    </div>\n</div>\n<h2 class="mt-2">About Trongate</h2>\n<div class="text-div">\n    <p>\n        <a href="https://trongate.io/" target="_blank">Trongate</a> is an open source project, written in PHP. The GitHub repository for Trongate is <a href="https://github.com/trongate/trongate-framework" target="_blank">here</a>. Contributions are welcome! If you\'re interested in learning how to build custom web applications with Trongate, a good place to start is The Learning Zone. The URL for the Learning Zone is: <a href="https://trongate.io/learning-zone" target="_blank">https://trongate.io/learning-zone</a>. <b>If you enjoy working with Trongate, all we ask is that you give Trongate a star on <a href="https://github.com/trongate/trongate-framework" target="_blank">GitHub</a>.</b> It really helps!\n    </p>\n    <p>\n        Finally, if you run into any issues or you require technical assistance, please do visit our free Help Bar, which is at: <a href="https://trongate.io/help_bar" target="_blank">https://trongate.io/help_bar</a>.\n    </p>\n</div>', 1723807486, 0, 1, 1);

-- Dumping structure for table attend.trongate_tokens
CREATE TABLE IF NOT EXISTS `trongate_tokens` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `token` varchar(125) DEFAULT NULL,
  `user_id` int(11) DEFAULT 0,
  `expiry_date` int(11) DEFAULT NULL,
  `code` varchar(3) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table attend.trongate_tokens: ~1 rows (approximately)
INSERT INTO `trongate_tokens` (`id`, `token`, `user_id`, `expiry_date`, `code`) VALUES
	(9, 'KLk7rHQmcxu4Gu3pwv5BddSDbDvJDmbj', 1, 1760587377, '0');

-- Dumping structure for table attend.trongate_users
CREATE TABLE IF NOT EXISTS `trongate_users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` varchar(32) DEFAULT NULL,
  `user_level_id` int(11) DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table attend.trongate_users: ~1 rows (approximately)
INSERT INTO `trongate_users` (`id`, `code`, `user_level_id`) VALUES
	(1, '5NJCkdymu57Byf9uQRzvptua48rjAuq2', 1);

-- Dumping structure for table attend.trongate_user_levels
CREATE TABLE IF NOT EXISTS `trongate_user_levels` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `level_title` varchar(125) DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table attend.trongate_user_levels: ~2 rows (approximately)
INSERT INTO `trongate_user_levels` (`id`, `level_title`) VALUES
	(1, 'admin'),
	(2, 'member');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
